version: '3.9'
services:
  web:
    image: braparison/carte-fillup-front
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m